name-template: 'Release ${{ nextRelease.version }}'
tag-template: 'v${{ nextRelease.version }}'
categories:
  - title: 'ğŸš€ Features'
    labels:
      - 'feature'
  - title: 'ğŸ› Bug Fixes'
    labels:
      - 'bug'
  - title: 'ğŸ›  Improvements'
    labels:
      - 'enhancement'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changes in this release
  $CHANGES
